openapi: "3.0.1"
info:
  title: "Hortz"
  version: "1.0"
paths:
  "/users":
    get:
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        payloadFormatVersion: "1.0"
        type: "AWS_PROXY"
        uri: ${lambda_getUsers_arn}